In [1]:
import pandas as pd
pd.set_option('display.float_format', lambda x: '%.3f' % x)

In [2]:
df=pd.read_csv(r'C:\Users\Jegadeesh\Downloads\Compressed\Projects\Highest Holywood Grossing Movies.csv')

In [3]:
df.head(2)

,Unnamed: 0,Title,Movie Info,Distributor,Release Date,Domestic Sales (in $),International Sales (in $),World Sales (in $),Genre,Movie Runtime,License
0,0,Star Wars: Episode VII - The Force Awakens (2015),"As a new threat to the galaxy rises, Rey, a de...",Walt Disney Studios Motion Pictures,"December 16, 2015",936662225,1132859475,2069521700,"['Action', 'Adventure', 'Sci-Fi']",2 hr 18 min,PG-13
1,1,Avengers: Endgame (2019),After the devastating events of Avengers: Infi...,Walt Disney Studios Motion Pictures,"April 24, 2019",858373000,1939128328,2797501328,"['Action', 'Adventure', 'Drama', 'Sci-Fi']",3 hr 1 min,PG-13

Rename Unnamed Column

In [4]:
df.rename(columns={'Unnamed: 0':'Index'},inplace=True)

In [5]:
df.head(2)

,Index,Title,Movie Info,Distributor,Release Date,Domestic Sales (in $),International Sales (in $),World Sales (in $),Genre,Movie Runtime,License
0,0,Star Wars: Episode VII - The Force Awakens (2015),"As a new threat to the galaxy rises, Rey, a de...",Walt Disney Studios Motion Pictures,"December 16, 2015",936662225,1132859475,2069521700,"['Action', 'Adventure', 'Sci-Fi']",2 hr 18 min,PG-13
1,1,Avengers: Endgame (2019),After the devastating events of Avengers: Infi...,Walt Disney Studios Motion Pictures,"April 24, 2019",858373000,1939128328,2797501328,"['Action', 'Adventure', 'Drama', 'Sci-Fi']",3 hr 1 min,PG-13

Set Index Column as Index

In [6]:
df.set_index('Index',inplace=True)

In [7]:
df.head(2)

,Title,Movie Info,Distributor,Release Date,Domestic Sales (in $),International Sales (in $),World Sales (in $),Genre,Movie Runtime,License
Index,,,,,,,,,,
0,Star Wars: Episode VII - The Force Awakens (2015),"As a new threat to the galaxy rises, Rey, a de...",Walt Disney Studios Motion Pictures,"December 16, 2015",936662225,1132859475,2069521700,"['Action', 'Adventure', 'Sci-Fi']",2 hr 18 min,PG-13
1,Avengers: Endgame (2019),After the devastating events of Avengers: Infi...,Walt Disney Studios Motion Pictures,"April 24, 2019",858373000,1939128328,2797501328,"['Action', 'Adventure', 'Drama', 'Sci-Fi']",3 hr 1 min,PG-13

In [8]:
df.describe()

       Domestic Sales (in $)  International Sales (in $)  World Sales (in $)
count                918.000                     918.000             918.000
mean           167746917.939               230143435.585       396866825.782
std            104036044.970               217601104.217       308262916.044
min             80360843.000                     260.000        81600000.000
25%            101607071.750                88456200.250       200556355.250
50%            132135096.000               163881928.000       301941607.000
75%            191390485.500               288557651.000       475071823.500
max            936662225.000              2086738578.000      2847246203.000

In [9]:
def to_million(x):
    return x/1000000
item=["Domestic Sales (in $)","International Sales (in $)","World Sales (in $)"]
for i in item:
    df[i]=df[i].apply(to_million)

Rename Columns to make it Million

In [10]:
df.rename(columns={'Domestic Sales (in $)':'Domestic Sales (in $M)','International Sales (in $)':'International Sales (in $M)','World Sales (in $)':'World Sales (in $M)'},inplace=True)

In [11]:
df.head()

,Title,Movie Info,Distributor,Release Date,Domestic Sales (in $M),International Sales (in $M),World Sales (in $M),Genre,Movie Runtime,License
Index,,,,,,,,,,
0,Star Wars: Episode VII - The Force Awakens (2015),"As a new threat to the galaxy rises, Rey, a de...",Walt Disney Studios Motion Pictures,"December 16, 2015",936.662,1132.859,2069.522,"['Action', 'Adventure', 'Sci-Fi']",2 hr 18 min,PG-13
1,Avengers: Endgame (2019),After the devastating events of Avengers: Infi...,Walt Disney Studios Motion Pictures,"April 24, 2019",858.373,1939.128,2797.501,"['Action', 'Adventure', 'Drama', 'Sci-Fi']",3 hr 1 min,PG-13
2,Avatar (2009),A paraplegic Marine dispatched to the moon Pan...,Twentieth Century Fox,"December 16, 2009",760.508,2086.739,2847.246,"['Action', 'Adventure', 'Fantasy', 'Sci-Fi']",2 hr 42 min,PG-13
3,Black Panther (2018),"T'Challa, heir to the hidden but advanced king...",Walt Disney Studios Motion Pictures,NaN,700.427,647.171,1347.598,"['Action', 'Adventure', 'Sci-Fi']",2 hr 14 min,NaN
4,Avengers: Infinity War (2018),The Avengers and their allies must be willing ...,Walt Disney Studios Motion Pictures,NaN,678.815,1369.544,2048.360,"['Action', 'Adventure', 'Sci-Fi']",2 hr 29 min,NaN

Find Null Values

In [12]:
df.isnull().sum()

Title                            0
Movie Info                       0
Distributor                      0
Release Date                   118
Domestic Sales (in $M)           0
International Sales (in $M)      0
World Sales (in $M)              0
Genre                            0
Movie Runtime                    0
License                        174
dtype: int64

In [13]:
df[df['Release Date'].isnull()]

,Title,Movie Info,Distributor,Release Date,Domestic Sales (in $M),International Sales (in $M),World Sales (in $M),Genre,Movie Runtime,License
Index,,,,,,,,,,
3,Black Panther (2018),"T'Challa, heir to the hidden but advanced king...",Walt Disney Studios Motion Pictures,NaN,700.427,647.171,1347.598,"['Action', 'Adventure', 'Sci-Fi']",2 hr 14 min,NaN
4,Avengers: Infinity War (2018),The Avengers and their allies must be willing ...,Walt Disney Studios Motion Pictures,NaN,678.815,1369.544,2048.360,"['Action', 'Adventure', 'Sci-Fi']",2 hr 29 min,NaN
5,Spider-Man: No Way Home (2021),"With Spider-Man's identity now revealed, Peter...",Sony Pictures Entertainment (SPE),NaN,675.813,868.643,1544.456,"['Action', 'Adventure', 'Fantasy', 'Sci-Fi']",2 hr 28 min,NaN
10,Incredibles 2 (2018),The Incredibles family takes on a new mission ...,Walt Disney Studios Motion Pictures,NaN,608.582,634.508,1243.089,"['Action', 'Adventure', 'Animation', 'Comedy',...",1 hr 58 min,NaN
16,Finding Dory (2016),Friendly but forgetful blue tang Dory begins a...,Walt Disney Studios Motion Pictures,NaN,486.296,542.275,1028.571,"['Adventure', 'Animation', 'Comedy', 'Family']",1 hr 37 min,NaN
...,...,...,...,...,...,...,...,...,...,...
890,Cheaper by the Dozen 2 (2005),"The Bakers, while on vacation, find themselves...",Twentieth Century Fox,NaN,82.571,47.583,130.155,"['Adventure', 'Comedy', 'Family']",1 hr 34 min,NaN
891,Mr. Holland's Opus (1995),A frustrated composer finds fulfillment as a h...,Walt Disney Studios Motion Pictures,NaN,82.570,23.700,106.270,"['Drama', 'Music']",2 hr 23 min,NaN
896,Bridge to Terabithia (2007),A preteen's life turns upside down when he bef...,Walt Disney Studios Motion Pictures,NaN,82.272,55.315,137.587,"['Drama', 'Family', 'Fantasy']",1 hr 36 min,NaN
903,MASH (1970),The staff of a Korean War field hospital use h...,Twentieth Century Fox,NaN,81.600,81.600,81.600,"['Comedy', 'Drama', 'War']",1 hr 56 min,NaN
912,Congo (1995),When an expedition to the African Congo ends i...,Paramount Pictures,NaN,81.022,71.000,152.022,"['Action', 'Adventure', 'Mystery', 'Sci-Fi']",1 hr 49 min,NaN

In [14]:
df.head()

,Title,Movie Info,Distributor,Release Date,Domestic Sales (in $M),International Sales (in $M),World Sales (in $M),Genre,Movie Runtime,License
Index,,,,,,,,,,
0,Star Wars: Episode VII - The Force Awakens (2015),"As a new threat to the galaxy rises, Rey, a de...",Walt Disney Studios Motion Pictures,"December 16, 2015",936.662,1132.859,2069.522,"['Action', 'Adventure', 'Sci-Fi']",2 hr 18 min,PG-13
1,Avengers: Endgame (2019),After the devastating events of Avengers: Infi...,Walt Disney Studios Motion Pictures,"April 24, 2019",858.373,1939.128,2797.501,"['Action', 'Adventure', 'Drama', 'Sci-Fi']",3 hr 1 min,PG-13
2,Avatar (2009),A paraplegic Marine dispatched to the moon Pan...,Twentieth Century Fox,"December 16, 2009",760.508,2086.739,2847.246,"['Action', 'Adventure', 'Fantasy', 'Sci-Fi']",2 hr 42 min,PG-13
3,Black Panther (2018),"T'Challa, heir to the hidden but advanced king...",Walt Disney Studios Motion Pictures,NaN,700.427,647.171,1347.598,"['Action', 'Adventure', 'Sci-Fi']",2 hr 14 min,NaN
4,Avengers: Infinity War (2018),The Avengers and their allies must be willing ...,Walt Disney Studios Motion Pictures,NaN,678.815,1369.544,2048.360,"['Action', 'Adventure', 'Sci-Fi']",2 hr 29 min,NaN

In [15]:
df.dtypes

Title                           object
Movie Info                      object
Distributor                     object
Release Date                    object
Domestic Sales (in $M)         float64
International Sales (in $M)    float64
World Sales (in $M)            float64
Genre                           object
Movie Runtime                   object
License                         object
dtype: object

In [16]:
df['Release Date']=pd.to_datetime(df['Release Date'])

Distributor Count

In [17]:
df['Distributor'].value_counts()

Warner Bros.                           158
Walt Disney Studios Motion Pictures    155
Universal Pictures                     119
Twentieth Century Fox                  117
Sony Pictures Entertainment (SPE)      101
Paramount Pictures                      99
DreamWorks                              21
New Line Cinema                         21
Lionsgate                               19
DreamWorks Distribution                 17
Metro-Goldwyn-Mayer (MGM)               12
TriStar Pictures                         9
Miramax                                  9
Revolution Studios                       8
Columbia Pictures                        7
Dimension Films                          7
The Weinstein Company                    6
Summit Entertainment                     5
Fox Searchlight Pictures                 4
STX Entertainment                        3
Orion Pictures                           3
Screen Gems                              3
United Artists                           2
Focus Features                           2
FilmDistrict                             2
Relativity Media                         1
United Artists Releasing                 1
IFC Films                                1
20th Century Studios                     1
USA Films                                1
Sony Pictures Classics                   1
Artisan Entertainment                    1
Newmarket Films                          1
Roadside Attractions                     1
Name: Distributor, dtype: int64

Distributor for top 100 Gross Movies

In [18]:
df[df.index <=49]

,Title,Movie Info,Distributor,Release Date,Domestic Sales (in $M),International Sales (in $M),World Sales (in $M),Genre,Movie Runtime,License
Index,,,,,,,,,,
0,Star Wars: Episode VII - The Force Awakens (2015),"As a new threat to the galaxy rises, Rey, a de...",Walt Disney Studios Motion Pictures,2015-12-16,936.662,1132.859,2069.522,"['Action', 'Adventure', 'Sci-Fi']",2 hr 18 min,PG-13
1,Avengers: Endgame (2019),After the devastating events of Avengers: Infi...,Walt Disney Studios Motion Pictures,2019-04-24,858.373,1939.128,2797.501,"['Action', 'Adventure', 'Drama', 'Sci-Fi']",3 hr 1 min,PG-13
2,Avatar (2009),A paraplegic Marine dispatched to the moon Pan...,Twentieth Century Fox,2009-12-16,760.508,2086.739,2847.246,"['Action', 'Adventure', 'Fantasy', 'Sci-Fi']",2 hr 42 min,PG-13
3,Black Panther (2018),"T'Challa, heir to the hidden but advanced king...",Walt Disney Studios Motion Pictures,NaT,700.427,647.171,1347.598,"['Action', 'Adventure', 'Sci-Fi']",2 hr 14 min,NaN
4,Avengers: Infinity War (2018),The Avengers and their allies must be willing ...,Walt Disney Studios Motion Pictures,NaT,678.815,1369.544,2048.360,"['Action', 'Adventure', 'Sci-Fi']",2 hr 29 min,NaN
5,Spider-Man: No Way Home (2021),"With Spider-Man's identity now revealed, Peter...",Sony Pictures Entertainment (SPE),NaT,675.813,868.643,1544.456,"['Action', 'Adventure', 'Fantasy', 'Sci-Fi']",2 hr 28 min,NaN
6,Titanic (1997),A seventeen-year-old aristocrat falls in love ...,Paramount Pictures,1997-12-19,659.364,1542.283,2201.647,"['Drama', 'Romance']",3 hr 14 min,PG-13
7,Jurassic World (2015),"A new theme park, built on the original site o...",Universal Pictures,2015-06-10,652.386,1018.131,1670.516,"['Action', 'Adventure', 'Sci-Fi']",2 hr 4 min,PG-13
8,The Avengers (2012),Earth's mightiest heroes must come together an...,Walt Disney Studios Motion Pictures,2012-04-25,623.358,895.458,1518.816,"['Action', 'Adventure', 'Sci-Fi']",2 hr 23 min,PG-13
9,Star Wars: Episode VIII - The Last Jedi (2017),The Star Wars saga continues as new heroes and...,Walt Disney Studios Motion Pictures,2017-12-13,620.181,712.517,1332.699,"['Action', 'Adventure', 'Fantasy', 'Sci-Fi']",2 hr 32 min,PG-13
10,Incredibles 2 (2018),The Incredibles family takes on a new mission ...,Walt Disney Studios Motion Pictures,NaT,608.582,634.508,1243.089,"['Action', 'Adventure', 'Animation', 'Comedy',...",1 hr 58 min,NaN
11,The Lion King (2019),"After the murder of his father, a young lion p...",Walt Disney Studios Motion Pictures,2019-07-11,543.638,1119.261,1662.899,"['Adventure', 'Animation', 'Drama', 'Family', ...",1 hr 58 min,PG
12,The Dark Knight (2008),When the menace known as the Joker wreaks havo...,Warner Bros.,2008-07-16,534.858,471.115,1005.974,"['Action', 'Crime', 'Drama', 'Thriller']",2 hr 32 min,PG-13
13,Rogue One: A Star Wars Story (2016),"In a time of conflict, a group of unlikely her...",Walt Disney Studios Motion Pictures,2016-12-14,532.177,523.880,1056.058,"['Action', 'Adventure', 'Sci-Fi']",2 hr 13 min,PG-13
14,Star Wars: Episode IX - The Rise of Skywalker ...,In the riveting conclusion of the landmark Sky...,Walt Disney Studios Motion Pictures,2019-12-18,515.203,558.947,1074.149,"['Action', 'Adventure', 'Fantasy', 'Sci-Fi']",2 hr 21 min,PG-13
15,Beauty and the Beast (2017),A selfish Prince is cursed to become a monster...,Walt Disney Studios Motion Pictures,2017-03-16,504.481,769.095,1273.576,"['Adventure', 'Family', 'Fantasy', 'Musical', ...",2 hr 9 min,PG
16,Finding Dory (2016),Friendly but forgetful blue tang Dory begins a...,Walt Disney Studios Motion Pictures,NaT,486.296,542.275,1028.571,"['Adventure', 'Animation', 'Comedy', 'Family']",1 hr 37 min,NaN
17,Frozen II (2019),"Anna, Elsa, Kristoff, Olaf and Sven leave Aren...",Walt Disney Studios Motion Pictures,2019-11-20,477.374,972.653,1450.027,"['Adventure', 'Animation', 'Comedy', 'Family',...",1 hr 43 min,PG
18,Star Wars: Episode I - The Phantom Menace (1999),Two Jedi escape a hostile blockade to find all...,Twentieth Century Fox,1999-05-19,474.545,552.538,1027.083,"['Action', 'Adventure', 'Fantasy', 'Sci-Fi']",2 hr 16 min,PG
19,Star Wars: Episode IV - A New Hope (1977),Luke Skywalker joins forces with a Jedi Knight...,Twentieth Century Fox,1977-05-25,460.999,195.752,775.398,"['Action', 'Adventure', 'Fantasy', 'Sci-Fi']",2 hr 1 min,PG
20,Avengers: Age of Ultron (2015),When Tony Stark and Bruce Banner try to jump-s...,Walt Disney Studios Motion Pictures,2015-04-22,459.006,943.804,1402.810,"['Action', 'Adventure', 'Sci-Fi']",2 hr 21 min,PG-13
21,The Dark Knight Rises (2012),Eight years after the Joker's reign of anarchy...,Warner Bros.,2012-07-19,448.139,633.004,1081.143,"['Action', 'Crime', 'Drama']",2 hr 44 min,PG-13
22,Shrek 2 (2004),Shrek and Fiona travel to the Kingdom of Far F...,DreamWorks Distribution,2004-05-19,441.226,487.535,928.761,"['Adventure', 'Animation', 'Comedy', 'Family',...",1 hr 33 min,PG
23,E.T. the Extra-Terrestrial (1982),A troubled child summons the courage to help a...,Universal Pictures,1982-06-11,435.111,304.204,792.911,"['Adventure', 'Family', 'Sci-Fi']",1 hr 55 min,PG
24,Toy Story 4 (2019),"When a new toy called ""Forky"" joins Woody and ...",Walt Disney Studios Motion Pictures,2019-06-20,434.038,639.357,1073.395,"['Adventure', 'Animation', 'Comedy', 'Family',...",1 hr 40 min,G
25,Captain Marvel (2019),Carol Danvers becomes one of the universe's mo...,Walt Disney Studios Motion Pictures,2019-03-06,426.830,701.633,1128.463,"['Action', 'Adventure', 'Sci-Fi']",2 hr 3 min,PG-13
26,The Hunger Games: Catching Fire (2013),Katniss Everdeen and Peeta Mellark become targ...,Lionsgate,2013-11-15,424.668,440.344,865.012,"['Action', 'Adventure', 'Drama', 'Sci-Fi', 'Th...",2 hr 26 min,PG-13
27,Pirates of the Caribbean: Dead Man's Chest (2006),Jack Sparrow races to recover the heart of Dav...,Walt Disney Studios Motion Pictures,2006-07-06,423.316,642.864,1066.180,"['Action', 'Adventure', 'Fantasy']",2 hr 31 min,PG-13
28,The Lion King (1994),Lion prince Simba and his father are targeted ...,Walt Disney Studios Motion Pictures,1994-06-15,422.784,640.828,1063.612,"['Adventure', 'Animation', 'Drama', 'Family', ...",1 hr 28 min,G
29,Jurassic World: Fallen Kingdom (2018),When the island's dormant volcano begins roari...,Universal Pictures,2018-06-06,417.720,892.747,1310.466,"['Action', 'Adventure', 'Sci-Fi']",2 hr 8 min,PG-13
30,Toy Story 3 (2010),The toys are mistakenly delivered to a day-car...,Walt Disney Studios Motion Pictures,2010-06-16,415.005,651.966,1066.971,"['Adventure', 'Animation', 'Comedy', 'Family',...",1 hr 43 min,NaN
31,Wonder Woman (2017),When a pilot crashes and tells of conflict in ...,Warner Bros.,2017-05-30,412.815,410.009,822.825,"['Action', 'Adventure', 'Fantasy', 'Sci-Fi', '...",2 hr 21 min,PG-13
32,Iron Man 3 (2013),When Tony Stark's world is torn apart by a for...,Walt Disney Studios Motion Pictures,2013-04-24,409.014,805.797,1214.811,"['Action', 'Adventure', 'Sci-Fi']",2 hr 10 min,PG-13
33,Captain America: Civil War (2016),Political involvement in the Avengers' affairs...,Walt Disney Studios Motion Pictures,2016-04-27,408.084,745.253,1153.337,"['Action', 'Adventure', 'Sci-Fi']",2 hr 27 min,PG-13
34,The Hunger Games (2012),Katniss Everdeen voluntarily takes her younger...,Lionsgate,2012-03-08,408.011,286.384,694.395,"['Action', 'Adventure', 'Sci-Fi', 'Thriller']",2 hr 22 min,PG-13
35,Spider-Man (2002),"When bitten by a genetically modified spider, ...",Sony Pictures Entertainment (SPE),2002-05-03,407.023,418.002,825.025,"['Action', 'Adventure', 'Sci-Fi']",2 hr 1 min,PG-13
36,Jumanji: Welcome to the Jungle (2017),Four teenagers are sucked into a magical video...,Sony Pictures Entertainment (SPE),2017-12-20,404.540,558.003,962.543,"['Action', 'Adventure', 'Comedy', 'Fantasy']",1 hr 59 min,PG-13
37,Jurassic Park (1993),A pragmatic paleontologist touring an almost c...,Universal Pictures,1993-06-11,404.215,629.714,1033.928,"['Action', 'Adventure', 'Sci-Fi', 'Thriller']",2 hr 7 min,PG-13
38,Transformers: Revenge of the Fallen (2009),Sam Witwicky leaves the Autobots behind for a ...,DreamWorks,2009-06-19,402.112,434.192,836.304,"['Action', 'Adventure', 'Sci-Fi']",2 hr 29 min,PG-13
39,Frozen (2013),When the newly crowned Queen Elsa accidentally...,Walt Disney Studios Motion Pictures,2013-11-22,400.953,880.555,1281.508,"['Adventure', 'Animation', 'Comedy', 'Family',...",1 hr 42 min,PG
40,Spider-Man: Far from Home (2019),"Following the events of Avengers: Endgame, Spi...",Sony Pictures Entertainment (SPE),2019-06-28,390.532,741.396,1131.928,"['Action', 'Adventure', 'Sci-Fi']",2 hr 9 min,PG-13
41,Guardians of the Galaxy Vol. 2 (2017),The Guardians struggle to keep together as a t...,Walt Disney Studios Motion Pictures,2017-04-25,389.813,473.943,863.756,"['Action', 'Adventure', 'Comedy', 'Sci-Fi']",2 hr 16 min,PG-13
42,Harry Potter and the Deathly Hallows: Part 2 (...,"Harry, Ron, and Hermione search for Voldemort'...",Warner Bros.,NaT,381.409,960.912,1342.322,"['Adventure', 'Fantasy', 'Mystery']",2 hr 10 min,NaN
43,Finding Nemo (2003),After his son is captured in the Great Barrier...,Walt Disney Studios Motion Pictures,2003-05-30,380.843,559.509,940.353,"['Adventure', 'Animation', 'Comedy', 'Family']",1 hr 40 min,NaN
44,Star Wars: Episode III - Revenge of the Sith (...,"Three years into the Clone Wars, the Jedi resc...",Twentieth Century Fox,2005-05-18,380.271,488.120,868.391,"['Action', 'Adventure', 'Fantasy', 'Sci-Fi']",2 hr 20 min,PG-13
45,The Lord of the Rings: The Return of the King ...,Gandalf and Aragorn lead the World of Men agai...,New Line Cinema,2003-12-17,377.846,768.185,1146.031,"['Action', 'Adventure', 'Drama', 'Fantasy']",3 hr 21 min,PG-13
46,Spider-Man 2 (2004),Peter Parker is beset with troubles in his fai...,Sony Pictures Entertainment (SPE),2004-06-30,373.586,415.391,788.976,"['Action', 'Adventure', 'Sci-Fi']",2 hr 7 min,PG-13
47,The Passion of the Christ (2004),Depicts the final twelve hours in the life of ...,Newmarket Films,2004-02-25,370.783,241.272,612.055,['Drama'],2 hr 7 min,R
48,The Secret Life of Pets (2016),The quiet life of a terrier named Max is upend...,Universal Pictures,2016-06-24,368.384,507.074,875.459,"['Adventure', 'Animation', 'Comedy', 'Family']",1 hr 27 min,PG
49,Despicable Me 2 (2013),"When Gru, the world's most super-bad turned su...",Universal Pictures,2013-06-20,368.065,602.701,970.766,"['Adventure', 'Animation', 'Comedy', 'Crime', ...",1 hr 38 min,PG

Value Count for Top 50 by two different Method

In [21]:
Df2=df[df.index <=49]

In [22]:
Df2['Distributor'].value_counts()

Walt Disney Studios Motion Pictures    24
Universal Pictures                      6
Sony Pictures Entertainment (SPE)       5
Twentieth Century Fox                   4
Warner Bros.                            4
Lionsgate                               2
Paramount Pictures                      1
DreamWorks Distribution                 1
DreamWorks                              1
New Line Cinema                         1
Newmarket Films                         1
Name: Distributor, dtype: int64

In [23]:
df[df.index <=49].Distributor.value_counts()

Walt Disney Studios Motion Pictures    24
Universal Pictures                      6
Sony Pictures Entertainment (SPE)       5
Twentieth Century Fox                   4
Warner Bros.                            4
Lionsgate                               2
Paramount Pictures                      1
DreamWorks Distribution                 1
DreamWorks                              1
New Line Cinema                         1
Newmarket Films                         1
Name: Distributor, dtype: int64

Top 100 Movies Based on Distributor

In [24]:
df[df.index <=99].Distributor.value_counts()

Walt Disney Studios Motion Pictures    36
Warner Bros.                           17
Twentieth Century Fox                  10
Sony Pictures Entertainment (SPE)       9
Universal Pictures                      8
Paramount Pictures                      5
Lionsgate                               4
DreamWorks                              4
New Line Cinema                         3
Summit Entertainment                    2
DreamWorks Distribution                 1
Newmarket Films                         1
Name: Distributor, dtype: int64

In [25]:
#Top 100 Movies Gross sum based on Distributor
df2=df[df.index <=99]
df3=df.groupby(['Distributor']).sum()
df3.sort_values(by=['World Sales (in $M)'],ascending=False)

,Domestic Sales (in $M),International Sales (in $M),World Sales (in $M)
Distributor,,,
Walt Disney Studios Motion Pictures,34098.332,48781.959,82372.099
Warner Bros.,25891.723,37741.575,63597.494
Twentieth Century Fox,19114.853,29338.267,48588.894
Universal Pictures,19316.009,26232.717,45602.645
Sony Pictures Entertainment (SPE),15764.875,21691.613,37456.488
Paramount Pictures,14484.466,18238.306,32443.523
DreamWorks,4040.554,6372.422,10412.976
Lionsgate,3424.851,4164.163,7498.506
New Line Cinema,3454.991,3611.355,7066.346
DreamWorks Distribution,2728.574,3086.066,5814.640
Metro-Goldwyn-Mayer (MGM),1528.265,2189.620,3717.884
Summit Entertainment,1163.978,1565.182,2729.159
TriStar Pictures,1062.086,1418.569,2483.548
Miramax,1081.876,976.715,2058.591
The Weinstein Company,761.994,1060.194,1822.188
Revolution Studios,898.340,544.096,1442.436
Columbia Pictures,956.287,680.419,1374.210
Dimension Films,691.875,531.130,1223.005
Fox Searchlight Pictures,474.354,643.070,1117.424
Orion Pictures,453.482,382.015,835.497
Newmarket Films,370.783,241.272,612.055
United Artists,210.952,291.068,502.019
STX Entertainment,326.473,140.882,467.356
Screen Gems,305.779,144.167,449.946
Focus Features,179.898,191.960,415.923
IFC Films,241.438,127.306,368.744
FilmDistrict,182.512,149.677,332.190
20th Century Studios,121.627,209.877,331.504
Artisan Entertainment,140.539,108.100,248.639
Relativity Media,83.504,143.400,226.904
Sony Pictures Classics,128.079,85.447,213.526
USA Films,124.116,83.400,207.516
United Artists Releasing,100.724,103.060,203.784
Roadside Attractions,83.482,2.605,86.087

In [26]:
#Top 100 Movies Gross sum based on Distributor
df[df.index<=99]

,Title,Movie Info,Distributor,Release Date,Domestic Sales (in $M),International Sales (in $M),World Sales (in $M),Genre,Movie Runtime,License
Index,,,,,,,,,,
0,Star Wars: Episode VII - The Force Awakens (2015),"As a new threat to the galaxy rises, Rey, a de...",Walt Disney Studios Motion Pictures,2015-12-16,936.662,1132.859,2069.522,"['Action', 'Adventure', 'Sci-Fi']",2 hr 18 min,PG-13
1,Avengers: Endgame (2019),After the devastating events of Avengers: Infi...,Walt Disney Studios Motion Pictures,2019-04-24,858.373,1939.128,2797.501,"['Action', 'Adventure', 'Drama', 'Sci-Fi']",3 hr 1 min,PG-13
2,Avatar (2009),A paraplegic Marine dispatched to the moon Pan...,Twentieth Century Fox,2009-12-16,760.508,2086.739,2847.246,"['Action', 'Adventure', 'Fantasy', 'Sci-Fi']",2 hr 42 min,PG-13
3,Black Panther (2018),"T'Challa, heir to the hidden but advanced king...",Walt Disney Studios Motion Pictures,NaT,700.427,647.171,1347.598,"['Action', 'Adventure', 'Sci-Fi']",2 hr 14 min,NaN
4,Avengers: Infinity War (2018),The Avengers and their allies must be willing ...,Walt Disney Studios Motion Pictures,NaT,678.815,1369.544,2048.360,"['Action', 'Adventure', 'Sci-Fi']",2 hr 29 min,NaN
...,...,...,...,...,...,...,...,...,...,...
95,Inception (2010),A thief who steals corporate secrets through t...,Warner Bros.,2010-07-15,292.576,544.261,836.837,"['Action', 'Adventure', 'Sci-Fi', 'Thriller']",2 hr 28 min,PG-13
96,Harry Potter and the Order of the Phoenix (2007),With their warning about Lord Voldemort's retu...,Warner Bros.,2007-07-11,292.353,649.819,942.172,"['Action', 'Adventure', 'Family', 'Fantasy', '...",2 hr 18 min,PG-13
97,The Twilight Saga: Breaking Dawn - Part 2 (2012),"After the birth of Renesmee/Nessie, the Cullen...",Lionsgate,2012-11-14,292.325,537.423,829.748,"['Adventure', 'Drama', 'Fantasy', 'Romance']",1 hr 55 min,PG-13
98,"The Chronicles of Narnia: The Lion, the Witch ...",Four kids travel through a wardrobe to the lan...,Walt Disney Studios Motion Pictures,2005-12-07,291.711,453.302,745.013,"['Adventure', 'Family', 'Fantasy']",2 hr 23 min,PG
99,Man of Steel (2013),An alien child is evacuated from his dying wor...,Warner Bros.,2013-06-12,291.046,377.000,668.046,"['Action', 'Adventure', 'Sci-Fi']",2 hr 23 min,PG-13